Replace hero image `<canvas>` with CSS animation
sourcecred/website pull request #5
Opened 2019-08-17 08:06 UTC by wchargin

Summary:
Using CSS animations has a number of benefits over a canvas:

  - The foundation is a vector format, not a raster format, so it
    renders correctly on all screen sizes and zoom settings.
  - Painting and interpolation is automatically handled by the browser.
    It’ll try to hit 60fps, but will throttle down correctly if it can’t
    hit that (rather than lagging).
  - CSS animations support easing, so changing from linear interpolation
    to smooth interpolation is a one-line change (and still has a lot of
    flexibility: see <https://easings.net/>).
  - The other logos use SVG, so now they can all share one codepath.
  - The code is significantly shorter, simpler, and more declarative.
    It’s about a dozen lines of CSS and a dozen more of JavaScript.
  - It doesn’t need JavaScript to run. No `componentDidMount`, either.

I’ve tried to emulate the old canvas logo’s structure and animated
qualities in this new version (though I did fix the ugly linear
interpolation). It’s pretty close, though not identical. Tweak to taste.

Test Plan:
A side-by-side screenshot of the canvas (left) and SVG animation (right)
clearly shows the quality difference; note pixelation on the left:

![Side-by-side still screenshot of the old (left) and new (right)][ss]

[ss]: https://user-images.githubusercontent.com/4317806/63208450-0cd74d80-c089-11e9-9701-fa127d7b6ec4.png

This video is of lower image quality, but shows the improved dynamics;
note on the left side a sharp transition when the first derivative of
the radius changes sign, compared to a smooth curve on the right side:
see [gfycat preview][gfy] or [download high-quality `.webm`][webm].

[gfy]: https://gfycat.com/sizzlinghonorablegoat
[webm]: https://github.com/sourcecred/website/files/3511777/logo_comparison.webm.gz

wchargin-branch: logo-css-animation

2019-08-17 08:07 UTC, wchargin commented
Depends on #3 for proper scaling behavior.

2019-08-17 08:27 UTC, wchargin commented
Also, let me know if you’d like me to just delete the old canvas code in
this same commit. That’d bring the diff from +45/−8 to +45/−127, which
is always nice. :-)

2019-08-17 15:15 UTC, teamdandelion requested changes
This PR implements animation in a way that's hard-coded to that particular logo, rather than correctly replicating the animation behavior in general. For example, consider how the animation should look if applied to the "data driven" medallion ([gyfcat](https://gfycat.com/sizzlingindolenteasternglasslizard)).

As such, I'd want to keep the canvas renderer around; I have an idea of an easter egg where when you click on the medallion, it transforms smoothly into another one, and I'd need the canvas renderer for that. For now, though, using the CSS animated version seems like a fine improvement. However, rather than having an animate option added to the render options (especially given that it only animates one particular logo), i'd rather hack something in for that logo in particular. E.g. have a hero medallion wrapper which just munges the svg to apply the needed class directly, but don't add it to the contract, unless css animations are getting implemented correctly for all of the logo configurations.

2019-08-17 15:44 UTC, wchargin commented
I actually started with a general-purpose animation, but tweaked it with
the goal of making the hero image look closer to the original canvas
animation at the cost of making the other animations look less great.
I didn’t save the original, but you can get back to something fairly
similar by applying this two-line patch on top of this PR:

```diff
diff --git a/src/logoSvg.js b/src/logoSvg.js
index 9c20980..de989ab 100644
--- a/src/logoSvg.js
+++ b/src/logoSvg.js
@@ -33,9 +33,7 @@ export function render(g: any, size: number, settings: RenderSettings) {
     .append("g")
     .attr("transform", `translate(${size / 2}, ${size / 2})`);
 
-  if (animate) {
-    internal.attr("class", "animated-logo");
-  }
+  internal.attr("class", "animated-logo");
 
   // Add background circle
   internal
@@ -68,7 +66,7 @@ export function render(g: any, size: number, settings: RenderSettings) {
       .attr("d", arc)
       .attr("fill", (d) => color(layer))
       .attr("class", "logo-ray")
-      .style("animation-delay", (d) => `${-(d.i % 2) * 5}s`);
+      .style("animation-delay", (d) => `${-(d.i / 10)}s`);
   }
 
   // Add the pupil
diff --git a/src/style.css b/src/style.css
index 60cdea7..4414f3f 100644
--- a/src/style.css
+++ b/src/style.css
@@ -137,7 +137,7 @@ p {
 }
 
 .animated-logo path.logo-ray {
-  animation: breathe 10s infinite both cubic-bezier(0.445, 0.05, 0.55, 0.95);
+  animation: breathe 2s infinite both cubic-bezier(0.445, 0.05, 0.55, 0.95);
 }
 
 @media (min-width: 750px) {
```

Here’s what it looks like: [gfycat preview][gfy], [high-quality `.ogv`][ogv].
(Pardon the lower quality screencast.)

[gfy]: https://gfycat.com/memorabledeafeningcatbird
[ogv]: https://github.com/sourcecred/website/files/3512157/homogeneous_animations.ogv.gz

2019-08-17 18:37 UTC, wchargin commented
I’ll certainly grant that this is lower quality and more prototype-y
than the bar that I usually strive for, which I thought was okay for
this experimental repository. But I’m happy to try to make it a bit more
principled and resubmit, or we can do that in a follow-up as you prefer.

2019-08-17 22:43 UTC, wchargin commented
> have a hero medallion wrapper which just munges the svg to apply the
> needed class directly, but don't add it to the contract

Yeah, this makes sense to me. Done: the `logoSvg` module is now modified
only to emit a bit more introspection data into the DOM. PTAL.

2019-08-17 22:44 UTC, wchargin commented
The CSS animation formulation also makes it pretty easy to experiment
with and debug live. While writing this patch:

  - I added `outline: thin blue solid` and `outline: thin red solid` to
    the two partitions of rays to make sure that I was styling what I
    thought I was.
  - I used the Chrome animations inspector to pause the animation and
    scrub back and forward on the timeline.
  - I used the normal styles inspector to see where styles were being
    overridden due to the cascade.
  - I made changes to the styles in the inspector and saw them
    instantly, without refreshing the page or losing my place in the
    animation. Coupled with the ability to pause the animation, this
    lets you tweak and explore at a pretty fine-grained level without
    needing to write any dedicated code.

2019-08-18 13:29 UTC, teamdandelion approved these changes
Looks good, thanks!

2019-08-18 17:25 UTC, merged